/**
 * Picklist / multi-picklist option sets, generated from
 * "YachtWay CRM - Proposed Field Catalog.xlsx" (Picklist Options sheet).
 * Keyed by the field-schema field key (camelCase). This is the source of
 * truth for every option field's declared options.
 */
export const FIELD_OPTIONS: Record<string, string[]> = {
  accountCurrency: [
    "USD",
    "EUR",
    "GBP",
    "AUD",
    "CAD",
    "CHF",
    "AED",
    "NZD",
  ],
  activeCompanyStatus: ["Active", "Pending", "Inactive"],
  approvedConditions: [
    "Address of Storage or Mooring Location",
    "Confirmation of intended use (recreational only, no commercial/charter use)",
    "Copy of Identification",
    "CSI (Condition & Serial Number) Inspection (if survey waived)",
    "Executed Purchase Agreement or Bill of Sale",
    "Full Marine Survey (Condition & Valuation)",
    "Insurance Binder naming lender as loss payee - Must meet lender liability and hull coverage minimums",
    "Manufacturer Certificate of Origin (for new vessels)",
    "Mechanical Survey (Engine, generator, propulsion systems)",
    "Most Recent Bank Statement (to verify funds to close)",
    "Personal Financial Statement",
    "Photo of Hull Identification Number (HIN)",
    "Photos of Engine Serial Numbers",
    "Proof of Down Payment (bank statement, wire confirmation, etc.)",
    "Proof of U.S. Coast Guard Documentation or State Registration",
    "Two Years of Tax Returns",
    "Other - Add to Approval Notes",
  ],
  boatShow: ["Newport Beach", "Palm Beach", "Palma", "Cannes", "Monaco", "FLIBS"],
  boatShowName: ["Newport Beach", "Palm Beach", "Palma", "Cannes", "Monaco", "FLIBS"],
  buildType: ["Series Production", "Full Custom"],
  category: ["Motor Yacht", "Sailing Yacht"],
  companySource: [
    "Boat Show",
    "Organic Google Search",
    "Paid Google Search",
    "Paid List",
    "Partner",
    "Phone",
    "PPC",
    "Referral",
    "Social",
    "Web",
    "Offline Sources",
    "YachtWay Invite",
    "EasyFund",
    "Studio Booking Page",
  ],
  companyStatus: ["Lead", "MQL", "SQL", "Active Customer", "Past Customer"],
  companyType: [
    "Dealer",
    "Brokerage",
    "Shipyard",
    "Lender",
    "Insurance Firm",
    "Marina",
    "Other",
    "Naval Designer / Architect",
    "Documentation Company",
  ],
  contactType: [
    "Buyer",
    "Broker",
    "Manager",
    "Closing Agent",
    "Lender",
    "Insurance Agent",
    "Other",
    "Admin",
    "Charter",
  ],
  coverages: ["Personal Accident Coverage", "Third Party Liability", "Protection & Indemnity", "Additional Assureds"],
  cruisingArea: [
    "Mediterranean Trading",
    "North Sea / European Atlantic Coast",
    "Caribbean, Florida",
    "USA East Coast & Canada (Excluding Florida)",
    "USA West Coast, Canada, Mexico",
    "Coastal Waters Europe",
    "Coastal Waters International",
  ],
  currency: [
    "USD",
    "EUR",
    "GBP",
    "AUD",
    "CAD",
    "CHF",
    "AED",
    "NZD",
  ],
  declineReason: [
    "Borrower Communication - Application Withdrawn by Borrower",
    "Borrower Communication - Borrower Decided Not to Move Forward",
    "Borrower Communication - Borrower Unreachable",
    "Borrower Communication - Borrower Unresponsive to Follow-Up",
    "Borrower Communication - Incomplete Application",
    "Collateral/Vessel - Ineligible Vessel Type (Houseboat, Liveaboard, etc.)",
    "Collateral/Vessel - Required Vessel Documentation Not Provided",
    "Collateral/Vessel - Survey Failed (Structural/Mechanical Issues)",
    "Collateral/Vessel - Vessel Too Old for Financing",
    "Collateral/Vessel - Vessel Valuation Too Low for Requested Loan",
    "Credit & Financial - Credit Score Below Minimum",
    "Credit & Financial - Debt-to-Income Ratio Too High",
    "Credit & Financial - Derogatory Credit",
    "Credit & Financial - Incomplete Financial Documentation",
    "Credit & Financial - Insufficient Income to Qualify",
    "Credit & Financial - Recent Bankruptcy or Foreclosure",
    "Credit & Financial - Unverifiable Income or Assets",
    "External Factors - Cash Purchase Instead",
    "External Factors - Decided to Delay Purchase",
    "External Factors - Financed Elsewhere",
    "External Factors - Switched to Different Product/Loan Type",
    "Loan Structure - Loan Amount Below Minimum Threshold",
    "Loan Structure - Loan Terms Not Accepted by Borrower",
    "Loan Structure - Loan-to-Value (LTV) Exceeds Policy Limits",
  ],
  easysignSubscriptionType: ["Monthly", "Pay-per-deal"],
  engineType: [
    "Outboard",
    "IPS Pod Drive",
    "Sterndrive",
    "Jet Drive",
    "Surface Drive",
    "Shaft Drive",
    "Sail Drive",
    "Electric",
    "Foil Drive",
    "Zeus Pod",
    "Axius",
    "Direct Drive",
    "Pod Drive",
    "Straight Shaft",
    "Inboard",
  ],
  eventDuration: ["Single Day", "Multi Day"],
  eventTimeZone: [
    "Africa/Abidjan",
    "Africa/Accra",
    "Africa/Addis_Ababa",
    "Africa/Algiers",
    "Africa/Asmara",
    "Africa/Bamako",
    "Africa/Bangui",
    "Africa/Banjul",
    "Africa/Bissau",
    "Africa/Blantyre",
    "Africa/Brazzaville",
    "Africa/Bujumbura",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/Conakry",
    "Africa/Dakar",
    "Africa/Dar_es_Salaam",
    "Africa/Djibouti",
    "Africa/Douala",
    "Africa/El_Aaiun",
    "Africa/Freetown",
    "Africa/Gaborone",
    "Africa/Harare",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Kampala",
    "Africa/Khartoum",
    "Africa/Kigali",
    "Africa/Kinshasa",
    "Africa/Lagos",
    "Africa/Libreville",
    "Africa/Lome",
    "Africa/Luanda",
    "Africa/Lubumbashi",
    "Africa/Lusaka",
    "Africa/Malabo",
    "Africa/Maputo",
    "Africa/Maseru",
    "Africa/Mbabane",
    "Africa/Mogadishu",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Niamey",
    "Africa/Nouakchott",
    "Africa/Ouagadougou",
    "Africa/Porto-Novo",
    "Africa/Sao_Tome",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Anguilla",
    "America/Antigua",
    "America/Araguaina",
    "America/Argentina/Buenos_Aires",
    "America/Argentina/Catamarca",
    "America/Argentina/Cordoba",
    "America/Argentina/Jujuy",
    "America/Argentina/La_Rioja",
    "America/Argentina/Mendoza",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
    "America/Aruba",
    "America/Asuncion",
    "America/Atikokan",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Blanc-Sablon",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Cayenne",
    "America/Cayman",
    "America/Chicago",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Costa_Rica",
    "America/Creston",
    "America/Cuiaba",
    "America/Curacao",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Dominica",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Fort_Nelson",
    "America/Fortaleza",
    "America/Glace_Bay",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Grenada",
    "America/Guadeloupe",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana/Indianapolis",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Juneau",
    "America/Kentucky/Louisville",
    "America/Kentucky/Monticello",
    "America/Kralendijk",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Lower_Princes",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Marigot",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/Montserrat",
    "America/Nassau",
    "America/New_York",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Nuuk",
    "America/Ojinaga",
    "America/Panama",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Port_of_Spain",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Sitka",
    "America/St_Barthelemy",
    "America/St_Johns",
    "America/St_Kitts",
    "America/St_Lucia",
    "America/St_Thomas",
    "America/St_Vincent",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Tijuana",
    "America/Toronto",
    "America/Tortola",
    "America/Vancouver",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "America/Yellowknife",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/McMurdo",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Asia/Aden",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Bahrain",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Brunei",
    "Asia/Chita",
    "Asia/Choibalsan",
    "Asia/Colombo",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Hebron",
    "Asia/Ho_Chi_Minh",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Kathmandu",
    "Asia/Khandyga",
    "Asia/Kolkata",
    "Asia/Krasnoyarsk",
    "Asia/Kuala_Lumpur",
    "Asia/Kuching",
    "Asia/Kuwait",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Muscat",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Phnom_Penh",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Riyadh",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ulaanbaatar",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vientiane",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yangon",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faroe",
    "Atlantic/Madeira",
    "Atlantic/Reykjavik",
    "Atlantic/South_Georgia",
    "Atlantic/St_Helena",
    "Atlantic/Stanley",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/Perth",
    "Australia/Sydney",
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Busingen",
    "Europe/Chisinau",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Guernsey",
    "Europe/Helsinki",
    "Europe/Isle_of_Man",
    "Europe/Istanbul",
    "Europe/Jersey",
    "Europe/Kaliningrad",
    "Europe/Kirov",
    "Europe/Kyiv",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/London",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Minsk",
    "Europe/Monaco",
    "Europe/Moscow",
    "Europe/Oslo",
    "Europe/Paris",
    "Europe/Podgorica",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/San_Marino",
    "Europe/Sarajevo",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Skopje",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Ulyanovsk",
    "Europe/Vaduz",
    "Europe/Vatican",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Europe/Zurich",
    "Indian/Antananarivo",
    "Indian/Chagos",
    "Indian/Christmas",
    "Indian/Cocos",
    "Indian/Comoro",
    "Indian/Kerguelen",
    "Indian/Mahe",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Indian/Mayotte",
    "Indian/Reunion",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Chuuk",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Funafuti",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Kanton",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Majuro",
    "Pacific/Marquesas",
    "Pacific/Midway",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Pohnpei",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Saipan",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
    "Pacific/Wake",
    "Pacific/Wallis",
    "UTC",
  ],
  eventType: ["Boat Show", "Open House", "Exclusive Event"],
  fuelType: ["Diesel", "Gas", "Electric", "Hybrid"],
  heatTier: ["Hot", "Warm", "Cold"],
  hullMaterial: ["Fiberglass", "Aluminium", "Steel", "Wood", "Composite", "Carbon Fiber"],
  hullType: ["Monohull", "Multihull"],
  intentTier: ["Low", "Medium", "High"],
  locationType: ["Marina", "Private Dock", "Other"],
  loginFrequencyTier: ["Daily", "Weekly", "Monthly", "Dormant"],
  monthlyIncomeRange: ["Under $10,000", "$10,000-$24,999", "$25,000-$49,999", "$50,000-$99,999", "$100,000-$499,999", "$500,000+"],
  opportunityStatus: ["Open", "Won", "Lost", "Abandoned"],
  platformRole: [
    "Customer",
    "Broker",
    "Shipyard",
    "Dealer",
    "Shipyard Manager",
    "Dealership Manager",
    "Brokerage Firm",
    "Admin",
  ],
  playbookUpsellTargets: [
    "3D Tour",
    "Photoshoot",
    "Reels",
    "Spotlights",
    "Website Promo Video",
    "Social Media Management",
    "Photo Editing",
    "Website Design",
    "Team Portraits",
    "EasySign",
    "EasyFund",
    "MasterCover",
    "Closing Services",
    "Registrations",
    "Financing - Referrals/White-label",
    "API Feed",
    "Add Brokers",
    "Add Offices",
    "YachtWay Drive",
    "CRM",
    "VATO",
    "eNotary",
  ],
  policyStatus: ["Renewed", "Denied/Rejected", "Policy Current", "Policy Lapsed"],
  prequalStatus: ["Pre-Qualified", "Not Qualified"],
  publicOrPrivate: ["Public", "Private"],
  purchaseRefinance: ["Purchase", "Refinance"],
  purchaseTimeframe: ["Immediately", "Within 1 month", "Within 3 months", "6+ months", "Just browsing"],
  salesStatus: [
    "Available",
    "Hidden",
    "Sale Pending",
    "Sold",
    "Withdrawn",
    "Active",
    "Draft",
  ],
  selfReportedRange: ["740 and up", "700 to 739", "660 to 699", "Below 660"],
  signupSource: [
    "Waylo Limit",
    "Email Link",
    "Website CTA",
    "EasyFund",
    "NautiX",
    "Boat Show",
    "Partner",
    "YachtWay Invite",
    "Referral",
    "Paid Search",
    "Organic Search",
    "Social",
    "Display",
    "Direct",
    "Other",
  ],
  // Marketing / segmentation tags. Used on both contacts and companies to build
  // email sending lists. dynamicOptions() also surfaces any ad-hoc tag already
  // present on a record, so this list is a starting set, not a hard limit.
  tags: [
    "Newsletter",
    "Product Updates",
    "VIP",
    "Boat Show Lead",
    "Studio Customer",
    "EasyFund Prospect",
    "MasterCover Prospect",
    "Webinar Attendee",
    "Churn Risk",
    "Do Not Contact",
  ],
  upsellTargetPriority1: [
    "3D Tour",
    "Photoshoot",
    "Reels",
    "Spotlights",
    "Website Promo Video",
    "Social Media Management",
    "Photo Editing",
    "Website Design",
    "Team Portraits",
    "EasySign",
    "EasyFund",
    "MasterCover",
    "Closing Services",
    "Registrations",
    "Financing - Referrals/White-label",
    "API Feed",
    "Add Brokers",
    "Add Offices",
    "YachtWay Drive",
    "CRM",
    "VATO",
    "eNotary",
  ],
  upsellTargetPriority2: [
    "3D Tour",
    "Photoshoot",
    "Reels",
    "Spotlights",
    "Website Promo Video",
    "Social Media Management",
    "Photo Editing",
    "Website Design",
    "Team Portraits",
    "EasySign",
    "EasyFund",
    "MasterCover",
    "Closing Services",
    "Registrations",
    "Financing - Referrals/White-label",
    "API Feed",
    "Add Brokers",
    "Add Offices",
    "YachtWay Drive",
    "CRM",
    "VATO",
    "eNotary",
  ],
  upsellTargetPriority3: [
    "3D Tour",
    "Photoshoot",
    "Reels",
    "Spotlights",
    "Website Promo Video",
    "Social Media Management",
    "Photo Editing",
    "Website Design",
    "Team Portraits",
    "EasySign",
    "EasyFund",
    "MasterCover",
    "Closing Services",
    "Registrations",
    "Financing - Referrals/White-label",
    "API Feed",
    "Add Brokers",
    "Add Offices",
    "YachtWay Drive",
    "CRM",
    "VATO",
    "eNotary",
  ],
  vesselFlagLocation: [
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "Argentina",
    "Austria",
    "Australia",
    "Aruba",
    "Aland Islands",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthelemy",
    "Bermuda",
    "Brunei Darussalam",
    "Bolivia, Plurinational State of",
    "Bonaire, Sint Eustatius and Saba",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos (Keeling) Islands",
    "Congo, the Democratic Republic of the",
    "Central African Republic",
    "Congo",
    "Switzerland",
    "Cote d'Ivoire",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cape Verde",
    "Curacao",
    "Christmas Island",
    "Cyprus",
    "Czechia",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia and the South Sandwich Islands",
    "Guatemala",
    "Guinea-Bissau",
    "Guyana",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "Korea, Republic of",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Lao People's Democratic Republic",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova, Republic of",
    "Montenegro",
    "Saint Martin (French part)",
    "Madagascar",
    "North Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn",
    "Palestine",
    "Portugal",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Romania",
    "Serbia",
    "Russian Federation",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sweden",
    "Singapore",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Sao Tome and Principe",
    "El Salvador",
    "Sint Maarten (Dutch part)",
    "Eswatini",
    "Turks and Caicos Islands",
    "Chad",
    "French Southern Territories",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "Timor-Leste",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkiye",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania, United Republic of",
    "Ukraine",
    "Uganda",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Holy See (Vatican City State)",
    "Saint Vincent and the Grenadines",
    "Venezuela, Bolivarian Republic of",
    "Virgin Islands, British",
    "Vietnam",
    "Vanuatu",
    "Wallis and Futuna",
    "Samoa",
    "Kosovo",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe",
  ],
  vesselInterestTypes: ["Motor Yacht", "Sailing Yacht"],
  vesselLocationPreference: [
    "Great Lakes",
    "Northeast",
    "California",
    "East Coast",
    "Northwest",
    "Florida - Gulf Coast",
    "Florida - East Coast",
    "Other - US",
    "Northern Europe",
    "Western Europe",
    "Central Europe",
    "Southern Europe",
    "Eastern Europe",
    "Balkans",
    "Central Asia",
    "Middle East",
    "Southern Asia",
    "Eastern Asia and Pacific",
    "Northern Africa",
    "Western Africa",
    "Middle Africa",
    "Eastern Africa",
    "Southern Africa",
    "Australia and New Zealand",
    "Caribbean",
    "Central America",
    "Mexico",
    "Canada",
    "Brazil",
    "Southern South America",
    "Northern South America",
    "Western South America",
  ],
  vesselType: ["Motor Yacht", "Sailing Yacht"],
  waterToys: [
    "Tender",
    "Waverunner",
    "SeaBobs",
    "Floating Pool",
    "Slide",
    "Foils",
    "Submarine",
    "Seaplane",
    "Helicopter",
    "Other",
  ],
};

/**
 * Rule: option fields must always show their declared options; if the platform
 * sends (or a record holds) a value that isn't listed, that value is added to
 * the option set so it can be shown and kept selected. `dynamicOptions` merges
 * declared options with any encountered values, de-duped, order preserved.
 */
export function dynamicOptions(
  declared: readonly string[] | undefined,
  ...present: (string | null | undefined)[]
): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const v of [...(declared ?? []), ...present]) {
    const s = (v ?? '').toString().trim();
    if (!s || seen.has(s)) continue;
    seen.add(s);
    out.push(s);
  }
  return out;
}

/** Convenience: the canonical company_status options. */
export const COMPANY_STATUS_OPTIONS = FIELD_OPTIONS.companyStatus ?? [];
