import type { Prisma } from "@prisma/client";
import { env } from "../env.js";
import { mailgunSendConfigured, sendMailgunMessage } from "../integrations/mailgun.js";
import { createCheckoutSession } from "../integrations/stripe.js";
import type { BillToParty } from "./invoiceService.js";

/**
 * Invoice send (A1) — CRM is the invoice system of record. On send we optionally
 * open a Stripe pay link (billingProvider='stripe'), render a simple branded HTML
 * invoice, and email it to the payer via Mailgun. Bank/check invoices
 * (billingProvider='manual') just email the invoice; finance records the payment
 * by hand when it arrives.
 *
 * PDF attachment is a fast-follow — the emailed HTML is the invoice for v1; a
 * rendered PDF (pdfPath) can be added without changing this contract.
 */

interface InvoiceLike {
  id: string;
  reference: string | null;
  currency: string;
  amount: Prisma.Decimal | number | null;
  dueDate: Date | null;
  billingProvider: string;
  companyId: string | null;
}

interface LineLike {
  description: string | null;
  productCode: string | null;
  quantity: Prisma.Decimal | number | null;
  unitPrice: Prisma.Decimal | number | null;
  totalPrice: Prisma.Decimal | number | null;
}

const money = (n: number, currency: string) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency }).format(n);

/** Render a minimal branded HTML invoice for the email body. */
export function renderInvoiceHtml(args: {
  invoice: InvoiceLike;
  party: BillToParty;
  lineItems: LineLike[];
  payLinkUrl: string | null;
}): string {
  const { invoice, party, lineItems, payLinkUrl } = args;
  const cur = invoice.currency;
  const rows =
    lineItems.length > 0
      ? lineItems
          .map((li) => {
            const qty = Number(li.quantity ?? 1);
            const unit = Number(li.unitPrice ?? 0);
            const total = li.totalPrice != null ? Number(li.totalPrice) : qty * unit;
            const label = li.description ?? li.productCode ?? "Item";
            return `<tr><td style="padding:6px 0">${label}</td><td style="text-align:right">${qty}</td><td style="text-align:right">${money(unit, cur)}</td><td style="text-align:right">${money(total, cur)}</td></tr>`;
          })
          .join("")
      : `<tr><td style="padding:6px 0">${invoice.reference ?? "Services"}</td><td style="text-align:right">1</td><td style="text-align:right"></td><td style="text-align:right">${money(Number(invoice.amount ?? 0), cur)}</td></tr>`;

  const due = invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString("en-US") : null;
  const payBtn = payLinkUrl
    ? `<p style="margin:24px 0"><a href="${payLinkUrl}" style="background:#0b5;color:#fff;padding:12px 20px;border-radius:6px;text-decoration:none">Pay online</a></p>`
    : `<p style="margin:24px 0;color:#555">Please remit payment by bank transfer using the reference above.</p>`;

  return `<!doctype html><html><body style="font-family:Arial,Helvetica,sans-serif;color:#222;max-width:640px;margin:0 auto">
  <h2>YachtWay — Invoice</h2>
  <p><strong>Ref:</strong> ${invoice.reference ?? invoice.id}${due ? ` &nbsp; <strong>Due:</strong> ${due}` : ""}</p>
  <p><strong>Bill to:</strong> ${party.name}${party.email ? ` &lt;${party.email}&gt;` : ""}</p>
  <table style="width:100%;border-collapse:collapse;margin-top:12px">
    <thead><tr style="border-bottom:1px solid #ccc"><th style="text-align:left">Description</th><th style="text-align:right">Qty</th><th style="text-align:right">Unit</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${rows}</tbody>
    <tfoot><tr style="border-top:2px solid #333"><td colspan="3" style="text-align:right;padding-top:8px"><strong>Total</strong></td><td style="text-align:right;padding-top:8px"><strong>${money(Number(invoice.amount ?? 0), cur)}</strong></td></tr></tfoot>
  </table>
  ${payBtn}
  <p style="color:#888;font-size:12px">YachtWay · This invoice was generated by the YachtWay CRM.</p>
  </body></html>`;
}

export interface SendInvoiceResult {
  payLinkUrl: string | null;
  emailed: boolean;
  providerMessageId: string | null;
}

/** Create a Stripe pay link (if the rail is stripe + the dealer has a customer) and
 *  email the rendered invoice. Pure I/O — the caller persists sentAt/status/url. */
export async function sendInvoiceEmail(args: {
  invoice: InvoiceLike;
  party: BillToParty;
  lineItems: LineLike[];
  stripeCustomerId: string | null;
}): Promise<SendInvoiceResult> {
  const { invoice, party } = args;

  // 1. Stripe pay link (payment mode) when the rail is stripe.
  let payLinkUrl: string | null = null;
  if (invoice.billingProvider === "stripe") {
    const session = await createCheckoutSession({
      mode: "payment",
      customerId: args.stripeCustomerId ?? undefined,
      amountMinor: Math.round(Number(invoice.amount ?? 0) * 100),
      currency: invoice.currency,
      description: invoice.reference ?? `Invoice ${invoice.id}`,
      clientReferenceId: invoice.id,
      metadata: { crm_invoice_id: invoice.id },
    });
    payLinkUrl = session.url;
  }

  // 2. Email the invoice (best-effort — a send failure shouldn't lose the pay link).
  let emailed = false;
  let providerMessageId: string | null = null;
  if (party.email && mailgunSendConfigured()) {
    const html = renderInvoiceHtml({ invoice, party, lineItems: args.lineItems, payLinkUrl });
    const from = `YachtWay Billing <billing@${env.MAILGUN_DOMAIN}>`;
    const res = await sendMailgunMessage({
      from,
      to: party.email,
      subject: `YachtWay invoice ${invoice.reference ?? invoice.id}`,
      html,
      crmMessageId: `invoice:${invoice.id}`,
    });
    emailed = true;
    providerMessageId = res.providerMessageId;
  }

  return { payLinkUrl, emailed, providerMessageId };
}
