/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ReferralsIndexRouteImport } from './routes/referrals.index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSignaturesRouteImport } from './routes/admin.signatures'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as BillingInvoicesIndexRouteImport } from './routes/billing.invoices.index'
import { Route as BillingEstimatesIndexRouteImport } from './routes/billing.estimates.index'
import { Route as ReferralsNewOppIdRouteImport } from './routes/referrals.new.$oppId'
import { Route as ReferralsIdEditRouteImport } from './routes/referrals.$id.edit'
import { Route as BillingShareTokenRouteImport } from './routes/billing.share.$token'
import { Route as BillingInvoicesNewRouteImport } from './routes/billing.invoices.new'
import { Route as BillingInvoicesIdRouteImport } from './routes/billing.invoices.$id'
import { Route as BillingInvoicePdfIdRouteImport } from './routes/billing.invoice-pdf.$id'
import { Route as BillingEstimatesNewRouteImport } from './routes/billing.estimates.new'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIndexRoute = ReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignaturesRoute = AdminSignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const BillingInvoicesIndexRoute = BillingInvoicesIndexRouteImport.update({
  id: '/billing/invoices/',
  path: '/billing/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingEstimatesIndexRoute = BillingEstimatesIndexRouteImport.update({
  id: '/billing/estimates/',
  path: '/billing/estimates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsNewOppIdRoute = ReferralsNewOppIdRouteImport.update({
  id: '/referrals/new/$oppId',
  path: '/referrals/new/$oppId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIdEditRoute = ReferralsIdEditRouteImport.update({
  id: '/referrals/$id/edit',
  path: '/referrals/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingShareTokenRoute = BillingShareTokenRouteImport.update({
  id: '/billing/share/$token',
  path: '/billing/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingInvoicesNewRoute = BillingInvoicesNewRouteImport.update({
  id: '/billing/invoices/new',
  path: '/billing/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingInvoicesIdRoute = BillingInvoicesIdRouteImport.update({
  id: '/billing/invoices/$id',
  path: '/billing/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingInvoicePdfIdRoute = BillingInvoicePdfIdRouteImport.update({
  id: '/billing/invoice-pdf/$id',
  path: '/billing/invoice-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingEstimatesNewRoute = BillingEstimatesNewRouteImport.update({
  id: '/billing/estimates/new',
  path: '/billing/estimates/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/callback': typeof CallbackRoute
  '/services': typeof ServicesRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/signatures': typeof AdminSignaturesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/billing/estimates/new': typeof BillingEstimatesNewRoute
  '/billing/invoice-pdf/$id': typeof BillingInvoicePdfIdRoute
  '/billing/invoices/$id': typeof BillingInvoicesIdRoute
  '/billing/invoices/new': typeof BillingInvoicesNewRoute
  '/billing/share/$token': typeof BillingShareTokenRoute
  '/referrals/$id/edit': typeof ReferralsIdEditRoute
  '/referrals/new/$oppId': typeof ReferralsNewOppIdRoute
  '/billing/estimates/': typeof BillingEstimatesIndexRoute
  '/billing/invoices/': typeof BillingInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/services': typeof ServicesRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/signatures': typeof AdminSignaturesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin': typeof AdminIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/events': typeof EventsIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/referrals': typeof ReferralsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/billing/estimates/new': typeof BillingEstimatesNewRoute
  '/billing/invoice-pdf/$id': typeof BillingInvoicePdfIdRoute
  '/billing/invoices/$id': typeof BillingInvoicesIdRoute
  '/billing/invoices/new': typeof BillingInvoicesNewRoute
  '/billing/share/$token': typeof BillingShareTokenRoute
  '/referrals/$id/edit': typeof ReferralsIdEditRoute
  '/referrals/new/$oppId': typeof ReferralsNewOppIdRoute
  '/billing/estimates': typeof BillingEstimatesIndexRoute
  '/billing/invoices': typeof BillingInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/callback': typeof CallbackRoute
  '/services': typeof ServicesRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/signatures': typeof AdminSignaturesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/billing/estimates/new': typeof BillingEstimatesNewRoute
  '/billing/invoice-pdf/$id': typeof BillingInvoicePdfIdRoute
  '/billing/invoices/$id': typeof BillingInvoicesIdRoute
  '/billing/invoices/new': typeof BillingInvoicesNewRoute
  '/billing/share/$token': typeof BillingShareTokenRoute
  '/referrals/$id/edit': typeof ReferralsIdEditRoute
  '/referrals/new/$oppId': typeof ReferralsNewOppIdRoute
  '/billing/estimates/': typeof BillingEstimatesIndexRoute
  '/billing/invoices/': typeof BillingInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/callback'
    | '/services'
    | '/admin/access'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/signatures'
    | '/admin/users'
    | '/companies/$id'
    | '/contacts/$id'
    | '/listings/$id'
    | '/opportunities/$id'
    | '/admin/'
    | '/calendar/'
    | '/companies/'
    | '/contacts/'
    | '/events/'
    | '/listings/'
    | '/opportunities/'
    | '/referrals/'
    | '/tasks/'
    | '/billing/estimates/new'
    | '/billing/invoice-pdf/$id'
    | '/billing/invoices/$id'
    | '/billing/invoices/new'
    | '/billing/share/$token'
    | '/referrals/$id/edit'
    | '/referrals/new/$oppId'
    | '/billing/estimates/'
    | '/billing/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/services'
    | '/admin/access'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/signatures'
    | '/admin/users'
    | '/companies/$id'
    | '/contacts/$id'
    | '/listings/$id'
    | '/opportunities/$id'
    | '/admin'
    | '/calendar'
    | '/companies'
    | '/contacts'
    | '/events'
    | '/listings'
    | '/opportunities'
    | '/referrals'
    | '/tasks'
    | '/billing/estimates/new'
    | '/billing/invoice-pdf/$id'
    | '/billing/invoices/$id'
    | '/billing/invoices/new'
    | '/billing/share/$token'
    | '/referrals/$id/edit'
    | '/referrals/new/$oppId'
    | '/billing/estimates'
    | '/billing/invoices'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/callback'
    | '/services'
    | '/admin/access'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/signatures'
    | '/admin/users'
    | '/companies/$id'
    | '/contacts/$id'
    | '/listings/$id'
    | '/opportunities/$id'
    | '/admin/'
    | '/calendar/'
    | '/companies/'
    | '/contacts/'
    | '/events/'
    | '/listings/'
    | '/opportunities/'
    | '/referrals/'
    | '/tasks/'
    | '/billing/estimates/new'
    | '/billing/invoice-pdf/$id'
    | '/billing/invoices/$id'
    | '/billing/invoices/new'
    | '/billing/share/$token'
    | '/referrals/$id/edit'
    | '/referrals/new/$oppId'
    | '/billing/estimates/'
    | '/billing/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ServicesRoute: typeof ServicesRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  ContactsIdRoute: typeof ContactsIdRoute
  ListingsIdRoute: typeof ListingsIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ReferralsIndexRoute: typeof ReferralsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  BillingEstimatesNewRoute: typeof BillingEstimatesNewRoute
  BillingInvoicePdfIdRoute: typeof BillingInvoicePdfIdRoute
  BillingInvoicesIdRoute: typeof BillingInvoicesIdRoute
  BillingInvoicesNewRoute: typeof BillingInvoicesNewRoute
  BillingShareTokenRoute: typeof BillingShareTokenRoute
  ReferralsIdEditRoute: typeof ReferralsIdEditRoute
  ReferralsNewOppIdRoute: typeof ReferralsNewOppIdRoute
  BillingEstimatesIndexRoute: typeof BillingEstimatesIndexRoute
  BillingInvoicesIndexRoute: typeof BillingInvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/': {
      id: '/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof ReferralsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signatures': {
      id: '/admin/signatures'
      path: '/signatures'
      fullPath: '/admin/signatures'
      preLoaderRoute: typeof AdminSignaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/billing/invoices/': {
      id: '/billing/invoices/'
      path: '/billing/invoices'
      fullPath: '/billing/invoices/'
      preLoaderRoute: typeof BillingInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/estimates/': {
      id: '/billing/estimates/'
      path: '/billing/estimates'
      fullPath: '/billing/estimates/'
      preLoaderRoute: typeof BillingEstimatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/new/$oppId': {
      id: '/referrals/new/$oppId'
      path: '/referrals/new/$oppId'
      fullPath: '/referrals/new/$oppId'
      preLoaderRoute: typeof ReferralsNewOppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/$id/edit': {
      id: '/referrals/$id/edit'
      path: '/referrals/$id/edit'
      fullPath: '/referrals/$id/edit'
      preLoaderRoute: typeof ReferralsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/share/$token': {
      id: '/billing/share/$token'
      path: '/billing/share/$token'
      fullPath: '/billing/share/$token'
      preLoaderRoute: typeof BillingShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/invoices/new': {
      id: '/billing/invoices/new'
      path: '/billing/invoices/new'
      fullPath: '/billing/invoices/new'
      preLoaderRoute: typeof BillingInvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/invoices/$id': {
      id: '/billing/invoices/$id'
      path: '/billing/invoices/$id'
      fullPath: '/billing/invoices/$id'
      preLoaderRoute: typeof BillingInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/invoice-pdf/$id': {
      id: '/billing/invoice-pdf/$id'
      path: '/billing/invoice-pdf/$id'
      fullPath: '/billing/invoice-pdf/$id'
      preLoaderRoute: typeof BillingInvoicePdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/estimates/new': {
      id: '/billing/estimates/new'
      path: '/billing/estimates/new'
      fullPath: '/billing/estimates/new'
      preLoaderRoute: typeof BillingEstimatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminSignaturesRoute: typeof AdminSignaturesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminSignaturesRoute: AdminSignaturesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ServicesRoute: ServicesRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  ContactsIdRoute: ContactsIdRoute,
  ListingsIdRoute: ListingsIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ReferralsIndexRoute: ReferralsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  BillingEstimatesNewRoute: BillingEstimatesNewRoute,
  BillingInvoicePdfIdRoute: BillingInvoicePdfIdRoute,
  BillingInvoicesIdRoute: BillingInvoicesIdRoute,
  BillingInvoicesNewRoute: BillingInvoicesNewRoute,
  BillingShareTokenRoute: BillingShareTokenRoute,
  ReferralsIdEditRoute: ReferralsIdEditRoute,
  ReferralsNewOppIdRoute: ReferralsNewOppIdRoute,
  BillingEstimatesIndexRoute: BillingEstimatesIndexRoute,
  BillingInvoicesIndexRoute: BillingInvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
